export const metadata = {
  title: "Part 2",
  description: "Generated by create next app",
};

export default function Page() {
    return (
        <div>
            <h1 className="text-center font-bold text-xl mt-20 after:content-['Bagger'] after:block">Channel: </h1>
            <input type="text" placeholder="Enter email" className="outline-0 border-2 border-solid border-black/80 focus:border-orange-400 transition-colors ease-in-out duration-300 mx-auto block  px-3 py-1.5 rounded placeholder:text-red-400"/>
            <button className="bg-orange-500 rounded block mt-10 mx-auto border border-white/50 border-solid hover:bg-orange-400 transition-colors ease-in-out duration-300">
                Hide modal
            </button>

            <div className="mx-auto w-50 h-15 mt-10 text-center bg-orange-400 rounded shadow-2xl font-bold p-5 flex items-center justify-center transition-colors ease-in-out duration-300 md:bg-blue-400 lg:bg-purple-400 xl:bg-red-400 2xl:bg-green-400">
                Adaptive block
            </div>
        </div>
    )
}
