export const metadata = {
  title: "Part 2",
  description: "Generated by create next app",
};

export default function Page() {
    return (
        <div>
            <h1 className="text-center font-bold text-xl mt-20 after:content-['Bagger'] after:block">Channel: </h1>
            <input type="text" placeholder="Enter email" className="outline-0 border-2 border-solid border-black/80 focus:border-orange-400 transition-colors ease-in-out duration-300 mx-auto block  px-3 py-1.5 rounded placeholder:text-red-400"/>
            <button className="bg-orange-500 rounded block mt-10 mx-auto border border-white/50 border-solid hover:bg-orange-400 transition-colors ease-in-out duration-300">
                Hide modal
            </button>
        </div>
    )
}
